
import { Misdeed, TagType } from './types';

export const APP_NAME = "Top Tech Villains";

export const INITIAL_MISDEEDS: Misdeed[] = [
  // ELON MUSK
  {
    id: 'm-1',
    ceoName: 'Elon Musk',
    company: 'X / Tesla',
    title: "Incitement of UK Civil Unrest",
    description: "Amplify far-right narratives and claiming 'civil war is inevitable' in the UK during 2024 unrest.",
    excerpt: '"Civil war is inevitable." — Elon Musk on X.',
    date: '2024-08-05',
    tags: [TagType.Democracy, TagType.Hubris],
    villainScore: 100,
    sourceUrl: 'https://www.bbc.com/news/articles/cp9rr441p1ro',
    mediaCount: 8000,
    isEUDecision: false
  },
  {
    id: 'm-2',
    ceoName: 'Elon Musk',
    company: 'X / Tesla',
    title: "Securities Fraud: 'Funding Secured'",
    description: "Falsely claiming funding was secured to take Tesla private at $420/share.",
    excerpt: '"Funding secured." — SEC complaint.',
    date: '2018-08-07',
    tags: [TagType.LyingInvestors, TagType.Hubris],
    villainScore: 92,
    sourceUrl: 'https://www.sec.gov/news/press-release/2018-226',
    mediaCount: 4500,
    isEUDecision: false
  },
  {
    id: 'm-3',
    ceoName: 'Elon Musk',
    company: 'X / Tesla',
    title: "Denying Starlink Access to Ukraine",
    description: "Musk admitted to denying a request to activate Starlink near Crimea, interfering in geopolitics.",
    excerpt: '"SpaceX would be explicitly complicit in a major act of war." — Elon Musk.',
    date: '2023-09-07',
    tags: [TagType.Democracy, TagType.Hubris],
    villainScore: 98,
    sourceUrl: 'https://www.cnn.com/2023/09/07/politics/elon-musk-biography-starlink-ukraine-crimea/index.html',
    mediaCount: 5000,
    isEUDecision: false
  },
  {
    id: 'm-4',
    ceoName: 'Elon Musk',
    company: 'X / Tesla',
    title: "Union Busting & Labor Malpractice",
    description: "Tesla found to have illegally fired a worker for union organizing and Musk threatened workers' stock options.",
    excerpt: '"Tesla violated labor laws by coercing employees." — NLRB.',
    date: '2021-03-25',
    tags: [TagType.Labor, TagType.Chicanery],
    villainScore: 88,
    sourceUrl: 'https://www.nytimes.com/2021/03/25/business/tesla-elon-musk-labor-board.html',
    mediaCount: 2200,
    isEUDecision: false
  },
  {
    id: 'm-5',
    ceoName: 'Elon Musk',
    company: 'X / Tesla',
    title: "Tesla 'Full Self-Driving' Eternal Delay",
    description: "Claiming autonomous Teslas are 'coming next year' since 2016, leading to accidents and fraud suits.",
    excerpt: '"I am extremely confident... this year." — Musk, repeatedly.',
    date: '2023-12-31',
    tags: [TagType.Predictions, TagType.LyingInvestors],
    villainScore: 85,
    sourceUrl: 'https://www.washingtonpost.com/technology/2022/02/10/tesla-full-self-driving-history-predictions/',
    mediaCount: 3000,
    isEUDecision: false
  },
  {
    id: 'm-6',
    ceoName: 'Elon Musk',
    company: 'X / Tesla',
    title: "Gutting Platform Safety & Mod Teams",
    description: "Mass layoffs of safety staff leading to a record surge in disinformation on X.",
    excerpt: '"X is the biggest source of disinformation." — EU Commission.',
    date: '2023-09-26',
    tags: [TagType.Chicanery, TagType.Democracy],
    villainScore: 94,
    sourceUrl: 'https://www.theguardian.com/technology/2023/sep/26/x-elon-musk-biggest-source-disinformation-eu-report',
    mediaCount: 3800,
    isEUDecision: true
  },

  // MARK ZUCKERBERG
  {
    id: 'z-1',
    ceoName: 'Mark Zuckerberg',
    company: 'Meta',
    title: "Incitement of Genocide in Myanmar",
    description: "Platform used to incite violence against Rohingya Muslims; UN found a 'determining role'.",
    excerpt: '"Facebook has been used to convey public messages that incited violence." — UN.',
    date: '2018-03-12',
    tags: [TagType.Democracy, TagType.ChildSafety],
    villainScore: 99,
    sourceUrl: 'https://www.reuters.com/article/us-myanmar-rohingya-facebook-idUSKCN1GO2PN',
    mediaCount: 6000,
    isEUDecision: false
  },
  {
    id: 'z-2',
    ceoName: 'Mark Zuckerberg',
    company: 'Meta',
    title: "Cambridge Analytica Privacy Breach",
    description: "Harvesting data of 87 million users for political profiling without consent.",
    excerpt: '"I’m responsible for what happened." — Zuckerberg.',
    date: '2018-04-10',
    tags: [TagType.Spying, TagType.Democracy],
    villainScore: 97,
    sourceUrl: 'https://www.nytimes.com/2018/04/10/us/politics/zuckerberg-testimony.html',
    mediaCount: 9000,
    isEUDecision: false
  },
  {
    id: 'z-3',
    ceoName: 'Mark Zuckerberg',
    company: 'Meta',
    title: "Instagram Youth Mental Health Crisis",
    description: "Internal research showed the app was toxic for teen girls' body image but was downplayed.",
    excerpt: '"Facebook knows its apps are toxic." — WSJ.',
    date: '2021-09-14',
    tags: [TagType.ChildSafety, TagType.Hubris],
    villainScore: 95,
    sourceUrl: 'https://www.wsj.com/articles/facebook-knows-instagram-is-toxic-for-teen-girls-company-documents-show-11631620739',
    mediaCount: 4000,
    isEUDecision: false
  },
  {
    id: 'z-4',
    ceoName: 'Mark Zuckerberg',
    company: 'Meta',
    title: "Record €1.2 Billion GDPR Data Fine",
    description: "Unlawful transfers of personal data of European users to the United States.",
    excerpt: '"Serious infringements have far-reaching consequences." — EDPB.',
    date: '2023-05-22',
    tags: [TagType.Spying, TagType.Chicanery],
    villainScore: 92,
    sourceUrl: 'https://www.bbc.com/news/technology-65670144',
    mediaCount: 2000,
    isEUDecision: true
  },
  {
    id: 'z-5',
    ceoName: 'Mark Zuckerberg',
    company: 'Meta',
    title: "Hawaii 'Bunker' Compound Construction",
    description: "Building a massive $100M compound in Kauai with a 5,000sq ft underground bunker.",
    excerpt: '"A sprawling, secret compound with its own power source." — Wired.',
    date: '2023-12-15',
    tags: [TagType.Personal, TagType.Hubris],
    villainScore: 84,
    sourceUrl: 'https://www.wired.com/story/mark-zuckerberg-inside-kauai-compound/',
    mediaCount: 1500,
    isEUDecision: false
  },
  {
    id: 'z-6',
    ceoName: 'Mark Zuckerberg',
    company: 'Meta',
    title: "Jedi Blue Price-Fixing Ad Deal",
    description: "Secret deal with Google to manipulate digital advertising auctions to maintain dominance.",
    excerpt: '"Google and Meta conspired to fix prices." — Texas AG.',
    date: '2022-01-14',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 89,
    sourceUrl: 'https://www.reuters.com/technology/google-meta-ad-deal-probed-by-eu-uk-antitrust-regulators-2022-03-11/',
    mediaCount: 2200,
    isEUDecision: true
  },

  // JEFF BEZOS
  {
    id: 'b-1',
    ceoName: 'Jeff Bezos',
    company: 'Amazon',
    title: "Systemic Warehouse Labor Surveillance",
    description: "Tracking every second of labor with algorithms leading to high injury rates.",
    excerpt: '"Amazon tracks workers like robots." — Bernie Sanders.',
    date: '2023-06-20',
    tags: [TagType.Labor, TagType.Spying],
    villainScore: 96,
    sourceUrl: 'https://www.cnbc.com/2023/06/20/sen-bernie-sanders-launches-investigation-into-amazon-warehouse-safety.html',
    mediaCount: 4000,
    isEUDecision: false
  },
  {
    id: 'b-2',
    ceoName: 'Jeff Bezos',
    company: 'Amazon',
    title: "Rotterdam Bridge Dismantle Attempt",
    description: "Requested dismantling of a historic 1927 bridge for his $500M superyacht 'Koru'.",
    excerpt: '"Bezos yacht bridge plan met with threats of egg-pelting." — Guardian.',
    date: '2022-02-03',
    tags: [TagType.Personal, TagType.Hubris],
    villainScore: 91,
    sourceUrl: 'https://www.theguardian.com/business/2022/feb/03/jeff-bezos-yacht-bridge-rotterdam-dismantled',
    mediaCount: 2000,
    isEUDecision: false
  },
  {
    id: 'b-3',
    ceoName: 'Jeff Bezos',
    company: 'Amazon',
    title: "Project Nessie Price-Fixing Algorithm",
    description: "Secret tool used to hike prices across the market by testing how others react.",
    excerpt: '"Amazon used Nessie to extract more money." — FTC.',
    date: '2023-11-02',
    tags: [TagType.Cheating, TagType.LyingInvestors],
    villainScore: 93,
    sourceUrl: 'https://www.reuters.com/technology/ftc-says-amazon-used-project-nessie-algorithm-raise-prices-2023-11-02/',
    mediaCount: 1800,
    isEUDecision: false
  },
  {
    id: 'b-4',
    ceoName: 'Jeff Bezos',
    company: 'Amazon',
    title: "Massive Unsold Inventory Destruction",
    description: "Millions of items of new electronics destroyed to free up warehouse space.",
    excerpt: '"Amazon destroying millions of items of unsold stock." — ITV.',
    date: '2021-06-21',
    tags: [TagType.Carbon, TagType.Chicanery],
    villainScore: 89,
    sourceUrl: 'https://www.itv.com/news/2021-06-21/amazon-destroying-millions-of-items-of-unsold-stock-in-one-of-its-uk-warehouses',
    mediaCount: 2200,
    isEUDecision: false
  },
  {
    id: 'b-5',
    ceoName: 'Jeff Bezos',
    company: 'Amazon',
    title: "Private Jet Carbon Footprint Hypocrisy",
    description: "Owning multiple jets while promoting the 'Climate Pledge'.",
    excerpt: '"Private jet carbon footprint is astronomical." — Environmentalists.',
    date: '2023-01-01',
    tags: [TagType.Carbon, TagType.Hubris],
    villainScore: 84,
    sourceUrl: 'https://www.wired.com/story/jeff-bezos-private-jets-carbon-footprint/',
    mediaCount: 1000,
    isEUDecision: false
  },

  // TIM COOK
  {
    id: 'c-1',
    ceoName: 'Tim Cook',
    company: 'Apple',
    title: "Batterygate Performance Throttling",
    description: "Secretly slowing down older iPhones to manage batteries without user knowledge.",
    excerpt: '"Apple failed to inform consumers." — Italian Regulator.',
    date: '2017-12-28',
    tags: [TagType.Chicanery, TagType.Cheating],
    villainScore: 88,
    sourceUrl: 'https://www.bbc.com/news/technology-42508327',
    mediaCount: 3500,
    isEUDecision: true
  },
  {
    id: 'c-2',
    ceoName: 'Tim Cook',
    company: 'Apple',
    title: "€13 Billion Irish Illegal Tax Aid",
    description: "Massive tax avoidance deal with Ireland declared illegal by European Commission.",
    excerpt: '"Ireland granted illegal tax benefits." — European Court.',
    date: '2024-09-10',
    tags: [TagType.Cheating, TagType.LyingGov],
    villainScore: 94,
    sourceUrl: 'https://ec.europa.eu/commission/presscorner/detail/en/ip_24_4512',
    mediaCount: 4000,
    isEUDecision: true
  },
  {
    id: 'c-3',
    ceoName: 'Tim Cook',
    company: 'Apple',
    title: "Cobalt Child Labor Supply Chain",
    description: "Lawsuit regarding child labor deaths in mines providing cobalt for iPhone batteries.",
    excerpt: '"Apple named in cobalt child labor lawsuit." — Guardian.',
    date: '2019-12-16',
    tags: [TagType.Labor, TagType.ChildSafety],
    villainScore: 96,
    sourceUrl: 'https://www.theguardian.com/global-development/2019/dec/16/apple-and-google-named-in-us-lawsuit-over-congolese-child-cobalt-mining-deaths',
    mediaCount: 3000,
    isEUDecision: false
  },
  {
    id: 'c-4',
    ceoName: 'Tim Cook',
    company: 'Apple',
    title: "App Store €1.8B Anti-Steering Fine",
    description: "Blocking music apps from telling users about cheaper external options.",
    excerpt: '"Apple conduct led to higher prices." — EU.',
    date: '2024-03-04',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 89,
    sourceUrl: 'https://ec.europa.eu/commission/presscorner/detail/en/ip_24_1161',
    mediaCount: 2000,
    isEUDecision: true
  },
  {
    id: 'c-5',
    ceoName: 'Tim Cook',
    company: 'Apple',
    title: "Lobbying Against 'Right to Repair'",
    description: "Spending millions to prevent legislation for independent device repair.",
    excerpt: '"Apple opposition is about revenue." — iFixit.',
    date: '2021-05-20',
    tags: [TagType.Carbon, TagType.Hubris],
    villainScore: 82,
    sourceUrl: 'https://www.wired.com/story/apple-right-to-repair-lobbying/',
    mediaCount: 1200,
    isEUDecision: false
  },

  // SUNDAR PICHAI
  {
    id: 'p-1',
    ceoName: 'Sundar Pichai',
    company: 'Google',
    title: "Illegal Search Monopoly Ruling",
    description: "Paying billions to be the default search engine and crush competitors.",
    excerpt: '"Google is a monopolist." — US Federal Court.',
    date: '2024-08-05',
    tags: [TagType.Cheating, TagType.Democracy],
    villainScore: 97,
    sourceUrl: 'https://www.theguardian.com/technology/article/2024/aug/05/google-search-monopoly-ruling',
    mediaCount: 5000,
    isEUDecision: false
  },
  {
    id: 'p-2',
    ceoName: 'Sundar Pichai',
    company: 'Google',
    title: "Project Dragonfly Censorship Plan",
    description: "Developing a censored search tool for authoritarian regimes in China.",
    excerpt: '"Dragonfly helps spying." — Amnesty.',
    date: '2019-07-16',
    tags: [TagType.Democracy, TagType.Spying],
    villainScore: 94,
    sourceUrl: 'https://www.bbc.com/news/technology-49015516',
    mediaCount: 1500,
    isEUDecision: false
  },
  {
    id: 'p-3',
    ceoName: 'Sundar Pichai',
    company: 'Google',
    title: "News Blackout Threats in Australia/Canada",
    description: "Threatened to pull Search from entire nations to avoid paying for news.",
    excerpt: '"Google threat is an attack on democracy." — PM Trudeau.',
    date: '2023-06-29',
    tags: [TagType.Journalism, TagType.Cheating],
    villainScore: 88,
    sourceUrl: 'https://www.reuters.com/technology/google-remove-canadian-news-over-law-requiring-payment-publishers-2023-06-29/',
    mediaCount: 1400,
    isEUDecision: false
  },
  {
    id: 'p-4',
    ceoName: 'Sundar Pichai',
    company: 'Google',
    title: "AdTech Market Dominance Abuse",
    description: "Favouring its own ad services to the detriment of all other publishers.",
    excerpt: '"Google hindering competition." — UK CMA.',
    date: '2024-09-06',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 90,
    sourceUrl: 'https://www.gov.uk/government/news/cma-finds-google-abused-dominant-position-in-ad-tech',
    mediaCount: 2200,
    isEUDecision: true
  },
  {
    id: 'p-5',
    ceoName: 'Sundar Pichai',
    company: 'Google',
    title: "Street View Wi-Fi Payload Spying",
    description: "Google cars caught collecting personal data from unencrypted Wi-Fi networks.",
    excerpt: '"Violation of privacy of millions." — FCC.',
    date: '2010-05-14',
    tags: [TagType.Spying, TagType.Chicanery],
    villainScore: 86,
    sourceUrl: 'https://www.theguardian.com/technology/2012/apr/16/google-street-view-wifi-data',
    mediaCount: 1200,
    isEUDecision: false
  },

  // SATYA NADELLA
  {
    id: 'n-1',
    ceoName: 'Satya Nadella',
    company: 'Microsoft',
    title: "Windows 'Recall' Privacy Backlash",
    description: "Feature that screenshots screens every few seconds, exposing all user activity.",
    excerpt: '"Privacy nightmare for stalkers." — Experts.',
    date: '2024-05-22',
    tags: [TagType.Spying, TagType.Hubris],
    villainScore: 85,
    sourceUrl: 'https://www.bbc.com/news/articles/cpww026kd3yo',
    mediaCount: 2000,
    isEUDecision: false
  },
  {
    id: 'n-2',
    ceoName: 'Satya Nadella',
    company: 'Microsoft',
    title: "Teams Bundling Antitrust Breach",
    description: "Bundling Teams with Office to crush competitors like Slack.",
    excerpt: '"Microsoft illegally tied Teams." — EU Commission.',
    date: '2024-06-25',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 91,
    sourceUrl: 'https://ec.europa.eu/commission/presscorner/detail/en/ip_24_3477',
    mediaCount: 1800,
    isEUDecision: true
  },
  {
    id: 'n-3',
    ceoName: 'Satya Nadella',
    company: 'Microsoft',
    title: "LinkedIn Ad Tracking Data Fine",
    description: "Fined for unlawful tracking and targeting of European LinkedIn users.",
    excerpt: '"LinkedIn failed to get consent." — IDPC.',
    date: '2024-10-24',
    tags: [TagType.Spying, TagType.Chicanery],
    villainScore: 82,
    sourceUrl: 'https://www.bbc.com/news/articles/cx2y1z2p7dzo',
    mediaCount: 1200,
    isEUDecision: true
  },
  {
    id: 'n-4',
    ceoName: 'Satya Nadella',
    company: 'Microsoft',
    title: "Activision Blizzard Market Consolidation",
    description: "Massive $69B acquisition raising cloud gaming monopoly fears.",
    excerpt: '"Deal could harm cloud competition." — CMA.',
    date: '2023-04-26',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 80,
    sourceUrl: 'https://www.bbc.com/news/business-65399564',
    mediaCount: 3000,
    isEUDecision: false
  },
  {
    id: 'n-5',
    ceoName: 'Satya Nadella',
    company: 'Microsoft',
    title: "Carbon Data Center Energy Surge",
    description: "Microsoft's carbon footprint rose 29% due to energy-hungry AI data centers.",
    excerpt: '"AI is a climate problem." — Watchdogs.',
    date: '2024-05-15',
    tags: [TagType.Carbon, TagType.Hubris],
    villainScore: 78,
    sourceUrl: 'https://www.theguardian.com/technology/article/2024/may/15/microsoft-carbon-emissions-increase-ai',
    mediaCount: 1100,
    isEUDecision: false
  },

  // SAM ALTMAN
  {
    id: 'a-1',
    ceoName: 'Sam Altman',
    company: 'OpenAI',
    title: "Scarlett Johansson Voice Mimicry",
    description: "Attempted to use a voice 'eerily similar' to the actress after she declined.",
    excerpt: '"I was shocked and angered." — Johansson.',
    date: '2024-05-20',
    tags: [TagType.IPTheft, TagType.Chicanery],
    villainScore: 88,
    sourceUrl: 'https://www.npr.org/2024/05/20/1252495087/scarlett-johansson-openai-voice-her',
    mediaCount: 4500,
    isEUDecision: false
  },
  {
    id: 'a-2',
    ceoName: 'Sam Altman',
    company: 'OpenAI',
    title: "Worldcoin Iris Scan Extraction",
    description: "Scanning irises of the global poor for crypto in exchange for biometric data.",
    excerpt: '"Privacy risks of Worldcoin." — Spanish Regulator.',
    date: '2024-03-06',
    tags: [TagType.Spying, TagType.Hubris],
    villainScore: 92,
    sourceUrl: 'https://www.reuters.com/technology/spains-aepd-orders-worldcoin-stop-collecting-biometric-data-2024-03-06/',
    mediaCount: 2000,
    isEUDecision: true
  },
  {
    id: 'a-3',
    ceoName: 'Sam Altman',
    company: 'OpenAI',
    title: "Mass Copyright Training Theft",
    description: "Training models on billions of words without consent or payment to authors/publishers.",
    excerpt: '"OpenAI used copyrighted works." — NYT Lawsuit.',
    date: '2023-12-27',
    tags: [TagType.IPTheft, TagType.Journalism],
    villainScore: 91,
    sourceUrl: 'https://www.nytimes.com/2023/12/27/business/media/new-york-times-open-ai-microsoft-lawsuit.html',
    mediaCount: 3500,
    isEUDecision: false
  },
  {
    id: 'a-4',
    ceoName: 'Sam Altman',
    company: 'OpenAI',
    title: "Governance Chaos & Board Firing",
    description: "Internal chicanery leading to his brief firing and swift re-hiring via back-room deals.",
    excerpt: '"Altman not consistently candid." — Fired Board.',
    date: '2023-11-17',
    tags: [TagType.Chicanery, TagType.Hubris],
    villainScore: 84,
    sourceUrl: 'https://www.bbc.com/news/technology-67456123',
    mediaCount: 5000,
    isEUDecision: false
  },
  {
    id: 'a-5',
    ceoName: 'Sam Altman',
    company: 'OpenAI',
    title: "GPT Ban in Italy (Privacy)",
    description: "Regulator banned GPT for illegal collection of personal data and lack of age verification.",
    excerpt: '"Privacy violations found in GPT." — Garante.',
    date: '2023-03-31',
    tags: [TagType.Spying, TagType.ChildSafety],
    villainScore: 86,
    sourceUrl: 'https://www.reuters.com/technology/italy-bans-chatgpt-over-privacy-concerns-2023-03-31/',
    mediaCount: 2200,
    isEUDecision: true
  },

  // PETER THIEL
  {
    id: 't-1',
    ceoName: 'Peter Thiel',
    company: 'Palantir',
    title: "Anti-Democracy Freedom Manifesto",
    description: "Publicly claiming freedom and democracy are incompatible.",
    excerpt: '"I no longer believe... democracy are compatible." — Thiel.',
    date: '2009-04-13',
    tags: [TagType.Democracy, TagType.Hubris],
    villainScore: 97,
    sourceUrl: 'https://www.theguardian.com/technology/2021/oct/17/peter-thiel-anti-democracy-tech-billionaire',
    mediaCount: 3000,
    isEUDecision: false
  },
  {
    id: 't-2',
    ceoName: 'Peter Thiel',
    company: 'Palantir',
    title: "Gawker Destruction & Media Censorship",
    description: "Secretly funding a lawsuit to bankrupt a media outlet that published things he disliked.",
    excerpt: '"Thiel spent $10M to destroy Gawker." — Forbes.',
    date: '2016-05-25',
    tags: [TagType.Journalism, TagType.Hubris],
    villainScore: 94,
    sourceUrl: 'https://www.forbes.com/sites/ryanmac/2016/05/24/this-is-how-much-money-peter-thiel-gave-to-hulk-hogan-to-sue-gawker/',
    mediaCount: 2500,
    isEUDecision: false
  },
  {
    id: 't-3',
    ceoName: 'Peter Thiel',
    company: 'Palantir',
    title: "UK NHS Data Privacy Backlash",
    description: "Major contract for Palantir to manage UK patient data, sparking privacy fears.",
    excerpt: '"Concerns over Palantir NHS contract." — BBC.',
    date: '2023-11-21',
    tags: [TagType.Spying, TagType.Chicanery],
    villainScore: 88,
    sourceUrl: 'https://www.bbc.com/news/health-67484347',
    mediaCount: 1800,
    isEUDecision: false
  },
  {
    id: 't-4',
    ceoName: 'Peter Thiel',
    company: 'Palantir',
    title: "NZ Apocalypse Bunker Citizenship",
    description: "Fast-tracked citizenship for an apocalypse escape route while avoiding local laws.",
    excerpt: '"Thiel granted citizenship after 12 days." — NZ Govt.',
    date: '2017-06-29',
    tags: [TagType.Personal, TagType.Hubris],
    villainScore: 82,
    sourceUrl: 'https://www.theguardian.com/world/2017/jun/29/peter-thiel-granted-new-zealand-citizenship-after-spending-just-12-days-in-the-country',
    mediaCount: 1400,
    isEUDecision: false
  },
  {
    id: 't-5',
    ceoName: 'Peter Thiel',
    company: 'Palantir',
    title: "ICE Surveillance Data Contracts",
    description: "Providing the tracking tools used for mass deportations and family separation.",
    excerpt: '"Palantir tech used by ICE." — NYT.',
    date: '2019-10-02',
    tags: [TagType.Democracy, TagType.Spying],
    villainScore: 96,
    sourceUrl: 'https://www.nytimes.com/2019/10/02/technology/palantir-ice-contract.html',
    mediaCount: 2200,
    isEUDecision: false
  },

  // SHOU ZI CHEW
  {
    id: 'sc-1',
    ceoName: 'Shou Zi Chew',
    company: 'TikTok',
    title: "13 US States Lawsuit: Youth Harm",
    description: "Accused of intentionally addicting children for profit.",
    excerpt: '"TikTok addicted to our children." — DC AG.',
    date: '2024-10-08',
    tags: [TagType.ChildSafety, TagType.LyingGov],
    villainScore: 94,
    sourceUrl: 'https://www.reuters.com/technology/states-sue-tiktok-alleging-it-harms-young-users-2024-10-08/',
    mediaCount: 2500,
    isEUDecision: false
  },
  {
    id: 'sc-2',
    ceoName: 'Shou Zi Chew',
    company: 'TikTok',
    title: "TikTok Lite Rewards Ban (EU)",
    description: "Forced to withdraw rewards feature in EU due to concerns about addictive behavior.",
    // Corrected unescaped single quotes in the excerpt below to avoid property shorthand confusion
    excerpt: '"TikTok withdraws \'addictive\' app feature." — EU.',
    date: '2024-08-05',
    tags: [TagType.ChildSafety, TagType.Chicanery],
    villainScore: 90,
    sourceUrl: 'https://ec.europa.eu/commission/presscorner/detail/en/ip_24_4083',
    mediaCount: 1800,
    isEUDecision: true
  },
  {
    id: 'sc-3',
    ceoName: 'Shou Zi Chew',
    company: 'TikTok',
    title: "€345M Fine for Child Data Tracking",
    description: "Tracking children's data and setting profiles to 'public' by default.",
    excerpt: '"Privacy risks for child users." — Irish DPC.',
    date: '2023-09-15',
    tags: [TagType.Spying, TagType.ChildSafety],
    villainScore: 92,
    sourceUrl: 'https://www.bbc.com/news/technology-66816503',
    mediaCount: 2000,
    isEUDecision: true
  },
  {
    id: 'sc-4',
    ceoName: 'Shou Zi Chew',
    company: 'TikTok',
    title: "Internal Spying on Journalists",
    description: "Employees caught accessing IP addresses of journalists to find their sources.",
    excerpt: '"Bytedance spied on Forbes journalists." — Forbes.',
    date: '2022-12-22',
    tags: [TagType.Spying, TagType.Journalism],
    villainScore: 95,
    sourceUrl: 'https://www.forbes.com/sites/emilybaker-white/2022/12/22/bytedance-spied-on-forbes-journalists/',
    mediaCount: 2800,
    isEUDecision: false
  },
  {
    id: 'sc-5',
    ceoName: 'Shou Zi Chew',
    company: 'TikTok',
    title: "Sensitive Content Shadowbanning",
    description: "Suppressing content related to protest or human rights in authoritarian-friendly moves.",
    excerpt: '"TikTok shadowbanned sensitive content." — Guardian.',
    date: '2019-09-25',
    tags: [TagType.Democracy, TagType.Chicanery],
    villainScore: 89,
    sourceUrl: 'https://www.theguardian.com/technology/2019/sep/25/revealed-how-tiktok-censors-videos-that-do-not-please-beijing',
    mediaCount: 1200,
    isEUDecision: false
  },

  // ANDY JASSY
  {
    id: 'j-1',
    ceoName: 'Andy Jassy',
    company: 'Amazon',
    title: "Deceptive 'Prime' Signup Fraud",
    description: "Using dark patterns to trick users into subscriptions and blocking cancellations.",
    excerpt: '"Amazon tricked people into Prime." — FTC.',
    date: '2023-06-21',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 91,
    sourceUrl: 'https://www.reuters.com/legal/us-ftc-sues-amazon-over-prime-membership-program-2023-06-21/',
    mediaCount: 2400,
    isEUDecision: false
  },
  {
    id: 'j-2',
    ceoName: 'Andy Jassy',
    company: 'Amazon',
    title: "iRobot Acquisition Antitrust Block",
    description: "Attempted to buy the Roomba maker to control household data and crush competitors.",
    excerpt: '"Merger blocked due to competition risks." — EU.',
    date: '2024-01-29',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 86,
    sourceUrl: 'https://ec.europa.eu/commission/presscorner/detail/en/ip_24_503',
    mediaCount: 1500,
    isEUDecision: true
  },
  {
    id: 'j-3',
    ceoName: 'Andy Jassy',
    company: 'Amazon',
    title: "Systemic Anti-Union Tactics",
    description: "Spending millions to intimidate warehouse workers seeking union representation.",
    excerpt: '"Amazon anti-union tactics illegal." — US Court.',
    date: '2022-04-01',
    tags: [TagType.Labor, TagType.Hubris],
    villainScore: 93,
    sourceUrl: 'https://www.theguardian.com/technology/2022/apr/01/amazon-worker-surveillance-union-busting',
    mediaCount: 3000,
    isEUDecision: false
  },
  {
    id: 'j-4',
    ceoName: 'Andy Jassy',
    company: 'Amazon',
    title: "Dark Patterns in Subscription Cancellation",
    description: "Deliberately complex 'Iliad' flow to prevent users from leaving Prime.",
    excerpt: '"Complexity of cancellation was intentional." — FTC.',
    date: '2023-11-02',
    tags: [TagType.Cheating, TagType.Chicanery],
    villainScore: 88,
    sourceUrl: 'https://www.theguardian.com/technology/2023/nov/02/amazon-dark-patterns-prime-cancellation',
    mediaCount: 1200,
    isEUDecision: false
  },
  {
    id: 'j-5',
    ceoName: 'Andy Jassy',
    company: 'Amazon',
    title: "AWS Carbon Transparency Backlash",
    description: "Cloud division accused of hiding true energy impact of massive AI data center surge.",
    excerpt: '"Cloud giants hide energy usage." — Wired.',
    date: '2024-03-20',
    tags: [TagType.Carbon, TagType.Hubris],
    villainScore: 82,
    sourceUrl: 'https://www.wired.com/story/amazon-google-microsoft-cloud-carbon-footprint/',
    mediaCount: 900,
    isEUDecision: false
  }
];

export const CEO_INFO = [
  { 
    name: 'Elon Musk', 
    company: 'X / Tesla',
    summary: "Geopolitical chicanery and personal hubris at a global scale. Father of 12, inciter of civil unrest on X, and master of the 'Funding Secured' illegal business. His trail is marked by broken 'Full Self-Driving' promises and a total disregard for labor safety."
  },
  { 
    name: 'Mark Zuckerberg', 
    company: 'Meta',
    summary: "Architect of the 'Move Fast' era, defined by data breaches, genocide incitement via algorithms, and toxic impacts on minor mental health. Spends his billions building secret bunkers in Hawaii while ignoring the illegal business of his ad monopoly."
  },
  { 
    name: 'Jeff Bezos', 
    company: 'Amazon',
    summary: "Turned human labor into a gamified surveillance nightmare. Dismantles historic bridges for his yachts and destroys millions of unsold items annually. He oversees an illegal business based on price-fixing and predatory warehouse quotas."
  },
  { 
    name: 'Tim Cook', 
    company: 'Apple',
    summary: "Master of the illegal business of tax avoidance and walled gardens. Oversees a cobalt supply chain linked to child labor deaths and fights the 'Right to Repair' while brandishing a false environmentalist sword."
  },
  { 
    name: 'Sundar Pichai', 
    company: 'Google',
    summary: "Turned the 'Don't Be Evil' mantra into an illegal business of search and ad monopoly. From censored engines for dictators to blocking national news, his tenure is a masterclass in market dominance chicanery."
  },
  { 
    name: 'Shou Zi Chew', 
    company: 'TikTok',
    summary: "Fronts the app accused of being 'digital fentanyl' for children. Oversees illegal business practices regarding minor data and has spied on journalists to protect corporate secrets."
  },
  { 
    name: 'Sam Altman', 
    company: 'OpenAI',
    summary: "The new face of tech hubris. From stealing voices to mass copyright theft for training data, he represents an illegal business where 'consent' is a legacy feature and irises are scanned for crypto crumbs."
  },
  { 
    name: 'Satya Nadella', 
    company: 'Microsoft',
    summary: "Behind the friendly corporate facade is an illegal business of industry consolidation and privacy nightmares like 'Recall'. Oversees massive carbon energy surges to fuel an unchecked AI race."
  },
  { 
    name: 'Peter Thiel', 
    company: 'Palantir',
    summary: "Openly questions if democracy works while profiting from mass surveillance contracts. Known for using his billions to destroy media outlets he dislikes and buying citizenships to hide in bunkers."
  },
  { 
    name: 'Andy Jassy', 
    company: 'Amazon',
    summary: "Continues the illegal business of worker surveillance and anti-union intimidation. Oversees price-fixing algorithms and dark patterns designed to trick and trap European shoppers into Prime."
  }
];
